name: CI/CD Pipeline with KIND

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-with-kind:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: |
        docker build -t wisecow:local .

    - name: Set up KIND
      uses: helm/kind-action@v1.8.0
      with:
        node_image: kindest/node:v1.26.0
        config: |
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
          - role: control-plane
            extraPortMappings:
            - containerPort: 80
              hostPort: 80
              protocol: TCP
            - containerPort: 443
              hostPort: 443
              protocol: TCP

    - name: Load image to KIND
      run: |
        kind load docker-image wisecow:local

    - name: Deploy to KIND
      run: |
        # Create namespace
        kubectl create namespace wisecow --dry-run=client -o yaml | kubectl apply -f -
        
        # Deploy the application
        kubectl apply -f k8s/
        
        # Wait for pods to be ready
        kubectl wait --for=condition=ready pod -l app=wisecow -n wisecow --timeout=120s
        
        # Get the service URL
        echo "Application deployed to KIND cluster"
        echo "Access the application at: http://localhost:80"
        
        # Show pods for verification
        kubectl get pods -n wisecow
        
        # Test the application
        curl -v http://localhost:80/
