name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: wisecow
  KUBE_NAMESPACE: wisecow
  KUBERNETES_VERSION: v1.27.0
  IMAGE_TAG: local

jobs:
  # CI Pipeline - Runs on PR and push to main
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Build Docker image
      run: |
        # Enable debugging
        set -ex
        
        echo "=== Building Image: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} ==="
        
        # Build the image
        docker buildx build \
          --platform linux/amd64 \
          -t ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          --load \
          --progress=plain \
          .
          
        echo "Image successfully built: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
        
    - name: Set up Kind Cluster
      run: |
        # Enable debugging
        set -ex
        
        echo "=== Setting up Kind Cluster ==="
        
        # Delete any existing Kind cluster
        kind delete cluster || true
        
        # Create Kind cluster using the config file
        kind create cluster --config=$GITHUB_WORKSPACE/kind-config.yaml --wait 5m
        
        # Verify the cluster is running
        kubectl cluster-info
        
        # Load the local image into the Kind cluster
        kind load docker-image ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        
        echo "=== Kind cluster setup complete ==="
        
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: ${{ env.KUBERNETES_VERSION }}
        
    - name: Install cert-manager
      run: |
        set -ex
        echo "=== Installing cert-manager ==="
        # Install cert-manager CRDs
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.crds.yaml
        
        # Create cert-manager namespace if it doesn't exist
        kubectl create namespace cert-manager --dry-run=client -o yaml | kubectl apply -f -
        
        # Install cert-manager
        kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.11.0/cert-manager.yaml
        
        # Wait for cert-manager to be ready
        kubectl wait --for=condition=available --timeout=300s deployment/cert-manager -n cert-manager
        kubectl wait --for=condition=available --timeout=300s deployment/cert-manager-cainjector -n cert-manager
        kubectl wait --for=condition=available --timeout=300s deployment/cert-manager-webhook -n cert-manager
        
    - name: Install KubeArmor CRDs
      run: |
        set -ex
        echo "=== Installing KubeArmor CRDs ==="
        # Install KubeArmor CRDs if the file exists
        if [ -f "k8s/kubearmor-crds.yaml" ]; then
          kubectl apply -f k8s/kubearmor-crds.yaml
        fi
        
    - name: Test Kubernetes Deployment
      run: |
        # Enable debugging
        set -ex
        
        echo "=== Testing Kubernetes Deployment ==="
        
        # Create namespace if it doesn't exist
        kubectl create namespace ${{ env.KUBE_NAMESPACE }} --dry-run=client -o yaml | kubectl apply -f -
        
        # Deploy application resources in the correct order
        # 1. First apply the cert-manager related resources
        if [ -f "k8s/cert-manager.yaml" ]; then
          kubectl apply -f k8s/cert-manager.yaml -n ${{ env.KUBE_NAMESPACE }}
        fi
        
        if [ -f "k8s/selfsigned-issuer.yaml" ]; then
          kubectl apply -f k8s/selfsigned-issuer.yaml -n ${{ env.KUBE_NAMESPACE }}
        fi
        
        # 2. Then apply the main application resources
        # Exclude cert-manager and KubeArmor specific files from the general apply
        for file in k8s/*.yaml; do
          if [[ "$file" != *"cert-manager.yaml"* ]] && 
             [[ "$file" != *"selfsigned-issuer.yaml"* ]] && 
             [[ "$file" != *"kubearmor"* ]]; then
            kubectl apply -f "$file" -n ${{ env.KUBE_NAMESPACE }}
          fi
        done
        
        # Wait for deployment to be ready
        kubectl wait --for=condition=available --timeout=300s deployment/wisecow -n ${{ env.KUBE_NAMESPACE }}
        
        # Get pod status
        echo "=== Pod Status ==="
        kubectl get pods -n ${{ env.KUBE_NAMESPACE }}
        
        # Test the application
        echo "=== Testing Application ==="
        kubectl run -i --rm --restart=Never test-curl --image=curlimages/curl -- \
          curl -s http://wisecow.wisecow.svc.cluster.local || true

  # CD Pipeline - Only runs on push to main
  cd:
    needs: ci
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: ${{ env.KUBERNETES_VERSION }}
        
    - name: Configure Kubernetes
      run: |
        # Enable debugging
        set -ex
        
        # Create .kube directory
        mkdir -p ~/.kube
        
        # Write the kubeconfig to a file
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        
        # Convert the kubeconfig to the correct format if needed
        if ! kubectl --kubeconfig=kubeconfig.yaml config view -o json &>/dev/null; then
          echo "Converting kubeconfig to proper format..."
          # If the file is a JSON array, extract the first item
          if head -n 1 kubeconfig.yaml | grep -q '^\['; then
            echo "Detected array format, converting to single object..."
            # Extract the first item from the array
            tail -n +2 kubeconfig.yaml | head -n -1 > kubeconfig-temp.yaml
            mv kubeconfig-temp.yaml kubeconfig.yaml
          fi
        fi
        
        # Move the kubeconfig to the default location
        cp kubeconfig.yaml ~/.kube/config
        chmod 600 ~/.kube/config
        
        # Verify kubectl is working
        echo "=== kubectl version ==="
        kubectl version --client
        
        echo "=== kubectl cluster-info ==="
        kubectl cluster-info
        
    - name: Configure Kubernetes
      run: |
        # Enable debugging
        set -ex
        
        # Create .kube directory
        mkdir -p ~/.kube
        
        # Write the kubeconfig to a file
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        
        # Convert the kubeconfig to the correct format if needed
        if ! kubectl --kubeconfig=kubeconfig.yaml config view -o json &>/dev/null; then
          echo "Converting kubeconfig to proper format..."
          # If the file is a JSON array, extract the first item
          if head -n 1 kubeconfig.yaml | grep -q '^\['; then
            echo "Detected array format, converting to single object..."
            # Extract the first item from the array
            tail -n +2 kubeconfig.yaml | head -n -1 > kubeconfig-temp.yaml
            mv kubeconfig-temp.yaml kubeconfig.yaml
          fi
        fi
        
        # Move the kubeconfig to the default location
        cp kubeconfig.yaml ~/.kube/config
        chmod 600 ~/.kube/config
        
        # Verify kubectl is working
        echo "=== kubectl version ==="
        kubectl version --client
        
        echo "=== kubectl cluster-info ==="
        kubectl cluster-info

    - name: Deploy to Kubernetes
      run: |
        # Enable debugging
        set -ex
        
        # Create a temporary directory for modified manifests
        mkdir -p tmp_manifests
        
        # Process deployment file to use the local image
        sed "s|image: .*|image: wisecow:local|" k8s/deployment.yaml > tmp_manifests/deployment.yaml
        
        # Verify the processed deployment file
        echo "=== Processed Deployment File ==="
        cat tmp_manifests/deployment.yaml
        
        # Apply Kubernetes manifests
        kubectl apply -f k8s/namespace.yaml
        kubectl apply -f tmp_manifests/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
        
        # Wait for rollout to complete
        kubectl rollout status deployment/wisecow -n ${{ env.KUBE_NAMESPACE }} --timeout=300s
        
        # Verify resources
        echo -e "\n=== Deployment Status ==="
        kubectl get deployments -n ${{ env.KUBE_NAMESPACE }}
        
        echo -e "\n=== Pods Status ==="
        kubectl get pods -n ${{ env.KUBE_NAMESPACE }}
        
        echo -e "\n=== Service Status ==="
        kubectl get svc -n ${{ env.KUBE_NAMESPACE }}
        
        echo -e "\n=== Ingress Status ==="
        kubectl get ingress -n ${{ env.KUBE_NAMESPACE }}
        
        # Get application URL
        echo -e "\n=== Application URL ==="
        kubectl get ingress -n ${{ env.KUBE_NAMESPACE }} -o jsonpath='{.items[0].spec.rules[0].host}'
